name: 'C++ CI lesson 1'


on:
  push:
    branches:
      - main
      - feature/github_actions
    paths:
      - 'lesson_1/**'
  workflow_dispatch:

# defaults:
#   run:
#     working-directory: ./01.CICD/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      ### Build ###
      - name: Build lesson_1
        working-directory: ./lesson_1/
        run: |
             sudo apt-get update && sudo apt-get install cmake libboost-test-dev -y
             cmake -B build -DPATCH_VERSION=${{ github.run_number }}
             cmake --build build
             cmake --build build --target test
             cmake --build build --target package
      
      ### Create release ###
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release - lesson_1 - ${{ github.run_number }}
          draft: false
          prerelease: false
      
      ### Upload release ###
      - name: Upload "lesson_1" Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lesson_1/build/helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
